### ISSUE TITLE
"Undo (#COUNT#)" and "Redo" not translatable?

### ISSUE THREAD

**Issue by psyafter** [voidlabs/mosaico#109]
I initialized "strings" option with different language.
All string translated but not undo and redo.

**Comment by bago** [comment]
Are you using the latest code?

**Comment by psyafter** [comment]
yes

**Comment by psyafter** [comment]
![maxthonsnap20160229200854](https://cloud.githubusercontent.com/assets/662215/13404041/8eef446a-df20-11e5-8b53-924ab5e2e7d6.png)

**Comment by bago** [comment]
Here is where the code deals with it:
https://github.com/voidlabs/mosaico/blob/master/src/js/undomanager/undomain.js#L15

Maybe the issue is the "plugin order":
https://github.com/voidlabs/mosaico/blob/master/src/js/app.js#L98

Can you test changing this line to 
```javascript
var extensions = [simpleTranslationPlugin, addUndoStackExtensionMaker(performanceAwareCaller), colorPlugin];
```

so that simpleTranslationPlugin is the first one?

Let me know if this fixes the issue, so I update the code.

**Comment by psyafter** [comment]
fine, now is fixed, thanks
