### ISSUE TITLE
Modal button text is invisible

### ISSUE THREAD

**Issue by tubaman** [voidlabs/mosaico#110]
The text is invisible on modal buttons.  Screenshot:
![mosaico_text_color_bug](https://cloud.githubusercontent.com/assets/197814/13412512/6063c088-df09-11e5-857f-18239b60c60e.png)

I think it's because the text color is the same as the button's background color.

**Comment by tubaman** [comment]
This is using mosaico sha [131dcc](https://github.com/voidlabs/mosaico/commit/131dcc) from master

**Comment by bago** [comment]
This happened because I updated TinyMCE but did not update its skin.
We probably just need to upload the skin json to http://skin.tinymce.com/ and download an updated skin... but maybe there are some more things to fix.

In the mean time, if you are in hurry, you can simply upload res/vendor/skins/gray-flat/skin.json to that website and download the updated skin.

Also, our "gray-flat" skin is a skin using the design of the old mosaico skin, not the new "material" skin.. so maybe we should create a complete new tinymce skin more in style with the new mosaico....skin.

Of course, contributions are welcome!
