### ISSUE TITLE
Help with fileupload plugin

### ISSUE THREAD

**Issue by JbalTero** [voidlabs/mosaico#118]
Great js library!

I have an issue during file upload. I cannot upload files due to csrf protection enabled and I need to add csrf data together with the file. How can I achieve this without having to disable the csrf and to exclude the upload endpoint, just using plugin? 

Thanks

**Comment by bago** [comment]
I guess this is a jqueryfileupload question, not a mosaico specific one.
Maybe have a look at http://stackoverflow.com/questions/27265998/pass-csrf-token-to-blueimp-fileupload

Otherwise try to find a solution for jquery-file-upload library. Once you know how to fix this altering mosaico code I'll explain how to change it via plugin.

FileUploading is handled here: https://github.com/voidlabs/mosaico/blob/master/src/js/bindings/fileupload.js#L285

**Comment by NJseo** [comment]
CrossOrigin

**Comment by JbalTero** [comment]
Thank you! I solved it.

For those who are having the same issue:

```
var ok = Mosaico.init({
    imgProcessorBackend: 'img',
    emailProcessorBackend: 'dl/',
    titleToken: "MOSAICO Responsive Email Designer",
    fileuploadConfig: {
        url: 'upload/',
        formData: { // <-- THIS HERE! credits: http://stackoverflow.com/questions/12074200/cant-verify-csrf-token-for-a-jquery-file-upload-ie-9-only-rails-3-app
            yourCsrfTokenName: yourCsrfTokenValue
        }
    },
  });

```

**Comment by bago** [comment]
Good! Thank you for sharing.
