### ISSUE TITLE
Suggesstions With Input Validation

### ISSUE THREAD

**Issue by NJseo** [voidlabs/mosaico#120]
The envoironment I am using Mosaico is multi-user so I am curious what other suggest I should use for input validation. I tried HTML Purifier, but even at its lowest settings it does too much that effects the display of the HTML newsletter.

**Comment by bago** [comment]
Write a proof of an exploit, so we can work around it. You can't purify if you don't know what you need to purify.

The only user-edited HTML rendered by mosaico is the one you input in the single text-areas via TinyMCE: you may have a look at TinyMCE options.

The full-html output is never used as "input", but always generated from the "model".

**Comment by NJseo** [comment]
Ok. Before save the produce HTML to database, the HTML gets stored in a local variable before it gets saved to the database. Because of this, a user could use any variety of XXS exploits to stored in a local storage. Everything that gets stored in the database or on the server needs to get checked, but when I tried HTMLentities and HTML purifier, the litmus previews for the email clients didn't work.

**Comment by bago** [comment]
XSS doesn't apply to content just because it is saved, but because content is then SERVED to other users.

So, you could simply not serve that content back to other users and you are safe (the generated HTML is not needed to start editing again the same email, but only to send it).

BTW my suggestions for content being loaded back to the editor (the model, not the output html):
1) check tinymce options to see how they deal with the "wyswyg" content
2) alter the "ko.bindingHandlers.wysiwyg" binding and the "ko.bindingHandlers.wysiwygOrHtml" so to filter html content for user-editable text being used as HTML

If you still want to purify the output html you will have to find a purifier that doen't alter the load of tricks and workarounds that are needed in html email to make it render fine on most devices. I don't have suggestions for that, sorry, just hard work for something not so interesting (email clients receiving the message will already add a lot of filtering/sandboxing in order to avoid "abuses").

**Comment by NJseo** [comment]
Thankyou for your feedback
