### ISSUE TITLE
Adding an Image URL instead of uploading from local

### ISSUE THREAD

**Issue by muralikrishna8** [voidlabs/mosaico#123]
Hi,

Is there any way where I can add the image URL rather than downloading that image to my local and then uploading to mosaico editor?

With this we don't need to store the images in the server, we can directly use the Image link from other site, rather than uploading to our server and linking.

**Comment by bago** [comment]
Mosaico does autoresizing of images. It would be hard to autoresize remote images (you would need to automatically download them and make them local...).

So if you are willing to add code for remote-downloading to the backend and add the UI to insert urls instead of using the drag&drop, then you could implement it.

I think it doesn't worth it, as it makes things more complex, but if you are a developer you can start digging in the code and I will give you some hints when you're stuck.

**Comment by gavrashenko** [comment]
I need to create mail for my partner. Partner can give me remote links to images for this mail, as mosaico doesn't support remote images, I have to upload them to my local server. But when I'll done with the email, all images urls will be local. For some reasons, I need to images urls with domain of my partner site. The simplest desicion is using remote images, which mosaico does not support. What should I do this case ? Replace ulrs manually after email creation?
