### ISSUE TITLE
How to use remote images in mail

### ISSUE THREAD

**Issue by gavrashenko** [voidlabs/mosaico#131]
Refering this issue  #123 I have a question.
I need to create mail for my partner. Partner can give me remote links to images for this mail, as mosaico doesn't support remote images, I have to upload them to my local server. But when I'll done with the email, all images urls will be local. For some reasons, I need to images urls with domain of my partner site. The simplest way is using remote images, which mosaico does not support. What should I do this case ? Replace ulrs manually after email creation? I no need to edit remote images, I just wanna to insert it in editor as is.

**Comment by bago** [comment]
Once you created your template with mosaico you can manually replace the IMG SRC attributes in the result, with whatever you want.

Make sure the new URL refer to images have the same size and aspect-ratio otherwise you'll break things.

Supporting remote urls in mosaico wouldn't fix your issue, because mosaico works with a backend to automatically resize/crop images, so if mosaico supported remote images then mosaico backend would support resize from remote images, but the final resized image would be still served by mosaico backend URL.

**Comment by gavrashenko** [comment]
Thanks, I thought so, only postprocessing for src attributes... But its very often issue when somebody makes template for mailing from specified domain with all hrefs/srcs from that domain. Maybe make sense to create some special static remote image item without any server processing, just insert those images with original size, in some very next release of course. Well, anyway thanks, If I'll make some useful stuff for this, i'll show it for you.

**Comment by bago** [comment]
IMHO it's a lot of work and the result is not usable enough. One of the most interesting feature Mosaico provides is the automatic resizing of images... altering the UI to let people provide external URL and making sure they use images having the correct size is a PITA. Just write an external tool  that copies the images to your domain and alter the src urls in the HTML before you send it.... it is much more error-proof and much easier.

**Comment by bago** [comment]
Or you can write your own backend method and make sure to upload images to your customer server and alter the SRC "on the fly" when people use the "download" button.
