### ISSUE TITLE
How to trigger Save event?

### ISSUE THREAD

**Issue by atezcan** [voidlabs/mosaico#133]
How can we trigger the save event in order to write a simple autosave every x seconds?

Thank you!

**Comment by bago** [comment]
The call "viewModel.save.execute();" will do the same thing as the save button.
Read https://github.com/voidlabs/mosaico/wiki/Mosaico-Plugins to know how to get access to the "viewModel" object.

**Comment by bago** [comment]
PS: I don't think it is GOOD to have an autosave in a tool with a save button. People could loose their work if they do experimental changes and then simply think to close without saving and reopen it to get the saved content (your autosave will discard what they thought they really saved).

Usually autosave saves in a different storage and then you have a tool to retrieve an autosaved content, otherwise you have "constant-save" (like Google Docs) but in this case you don't give the use a save button because everything they do is saved automatically.
