### ISSUE TITLE
images uploading, but not resizing

### ISSUE THREAD

**Issue by elfeffe** [voidlabs/mosaico#153]
The project is great, but I think it will be hard to grow since is very difficult to make it run the first time.
I have the same problem that was reported before

Loading "phantom-thumbnailer-editor.js" tasks...ERROR
>> Error: Cannot find module 'webpage'

And, I don't if it's related or not, it uploads the files, but doesn't resize anything.
Any idea?
I'm using Mac and Ubuntu 14.04, tried with both.

**Comment by bago** [comment]
Well, i'm sure it's harder to write an editor like this from scratch! And now it is opensource so everyone can contribute improvements in order to make it easier to "start-up".

You didn't report if "convert" command in your environment works. You also failed to report npm version, node version and other things are mandatory to open an issue (read the Readme and complete your support request according to what you find written there).

**Comment by elfeffe** [comment]
I found that the problem was Imagemagick, it was installed on the Ubuntu virtual machine, but not in the Mac. And as it runs on "local", It needs Imagemagick on the Mac.

I also discovered that emails are being sent without image, but that's because all images points to 127.0.0.1

I share that two points because they can help someone.

The project is great, but it really needs a stronger php backend.
I will find some time to help with that.

**Comment by bago** [comment]
Mosaico has not been designed to use on a "local computer". It is designed to be deployed on a serer. In fact it is a library developed for developers and each developers will have to develop his own backend depending on their needs... So the scope of this library is narrow.. anyone can create a "bigger" project that will use Mosaico (e.g: civicrm is working on including mosaico in their CRM, mailtrain is evaluating integrating mosaico in their product, and so on)

BTW whenever someone submit tickets without having read the Readme I spend some of my time answering answers instead of developing new features or make it easier to use it ;-)
