### ISSUE TITLE
Template resource URLs, Alternatives to mo-standalone

### ISSUE THREAD

**Issue by emu42** [voidlabs/mosaico#171]
Hello,

I am currently working on integrating Mosaico with a Java backend. The URLs in this environment are very different from what Mosaico apparently uses out-of-the-box. I especially need to alter paths to template resources which cannot be build relative to the current page in Javascript. All I'm asking for is a clue on where to even start making the needed modifications.

Then there's the question of rendering Mosaico on a div rather than the body tag. It seems the CSS class "mo-standalone" does not do me any good when used on a div (which I need because there's menus and stuff rendering by the Java code on the same page as the editor). Are there other "mo-XXX" CSS classes for this purpose?

Thanks in advance!

Kind regards,
 Edmund

**Comment by bago** [comment]
You can add a   <base href="yoururl"> in the editor.html and pass to "Mosaico.init" the option "document_base_url" with the same url.

```
  var ok = Mosaico.init({
    imgProcessorBackend: yourimgbackendurl,
    emailProcessorBackend: youremailprocessorbackendurl,
    fileuploadConfig: {
      url: youruploadbackendurl,
    },
    document_base_url: yourdocumentbaseurl
  });
```
About appending to a div, try altering the code here:
https://github.com/voidlabs/mosaico/blob/master/src/js/app.js#L114

You'll have to rebuild the library. Let me know if this works or not (I believe you may have issues using a div instead of the body as it was not something taken into consideration when developing the library)

**Comment by emu42** [comment]
The document_base_url parameter does not seem to have any effect at all. Specifically, I was hoping it would alter the path where Mosaico tries to load its templates from, but that URL still seems to be build relative to the browser's current document (which in my case is complete bogus, because my pages have parameters appended to the URL in '/key1/value1/key2/value2/...' style).

Also, I have been looking for a full list of Mosaico init parameters. Are these documented anywhere?

I have not had any luck with the div so far either (it currently stays empty), so right now I am working around that with an IFrame. Not pretty, but it works for now.

**Comment by bago** [comment]
Try adding a base href tag to your html.
About the template path I think you can pass an absolute url for the template path, too.

I'm sorry you are right about document_base_url not doing anything in mosaico: it is an option of an internal plugin I wrote in order to make mosaico use only relative paths.

**Comment by emu42** [comment]
The absolute template path works fine. Thanks! I am also using absolute URLs for the backend (imgProcessorBackend, emailProcessorBackend and fileuploadConfig). 

So far so good. I hope I won't see any more relative paths now. ;)

**Comment by bago** [comment]
Good!
