### ISSUE TITLE
File manager for mosaico [help wanted]

### ISSUE THREAD

**Issue by nabenzine** [voidlabs/mosaico#186]
Hi, 

First of all thank you for you amazing work, I am looking for an alternative to MoxieManager,  I have already replaced the image editor with Aviary, And now I need to find a file manager **mainly to upload files and get directly their links** , and optionally handle uploaded files/images if possible.

So any suggestion is more than welcome?  anyone had already implemented this? if so, I would be grateful if someone could share his code.

Thank you.

**Comment by bago** [comment]
I guess the main problem is that GPL version of mosaico is not compatible with "proprietary" client side javascript libraries like Aviary or MoxieManager. Using Mosaico GPL you are required to opensource the code you integrate with it.. and given you can't opensource (under a compatible license) Aviary or MoxieManager then you can't integrate them. That said, I'm not a lawyer, so I just wanted to "share" my opinion about that but I'm simply a developer.

Technically it should be easy to integrate both: I did that for MoxieManager (integrated to the commercial non-GPL version of mosaico) in order to use their Image editing tool (not the file browser).

**Comment by bago** [comment]
PS: maybe you should ask Aviary and/or MoxieManager if their clientside javascript can be redistributed under the GPLv3 or compatible license.

**Comment by nabenzine** [comment]
Thank you for you answer @bago, but besides the license problem, do you know any alternatives, cause MoxieManager is a paying solution

**Comment by bago** [comment]
I'm sorry, finding an opensource file manager for the web is not the scope of this project.
I know this one, but never used it: http://www.responsivefilemanager.com/
