### ISSUE TITLE
Can't upload images

### ISSUE THREAD

**Issue by lukaszrogut** [voidlabs/mosaico#188]
Hi,

I have read Readme file.
I am pretty sure that my server has imageMagick but I still can not upload images
http://p7.ewitryna.pl/mosaico/

On local host everything works fine.

Any suggestions?

Thank you for help

**Comment by bago** [comment]
I see that sites is running "IdeaWebServer" and not node, so you didn't deploy the backend. You probably are not even allowed to do that on that host.

Ask your provider how/if you can run Node.js applications or otherwise try the php backend (third party backend for mosaico): you see references to this in the readme.

https://github.com/voidlabs/mosaico/wiki/Serving-Mosaico
