### ISSUE TITLE
big toolbar for title bug

### ISSUE THREAD

**Issue by nabenzine** [voidlabs/mosaico#199]
Hi,

I wanted to add the big toolbar to titles as well, so I've changed 
`<span style="color: #3f3f3f; -ko-color: @titleTextStyle.color"; data-ko-editable="titleText" >
 Title 
</span>
`
to
`<div style="color: #3f3f3f; -ko-color: @titleTextStyle.color"; data-ko-editable="titleText">
 Title 
</div> 
`

![image](https://cloud.githubusercontent.com/assets/7820285/17970617/aebd1e6e-6ad7-11e6-9194-01f10dc2be93.png)

**It's working well, but when I remove the block or move it I've got this errors** 

![image](https://cloud.githubusercontent.com/assets/7820285/17970590/964c7a82-6ad7-11e6-807b-a8f4d258e4f9.png)

Any idea what cause this ?

Thank you in advance

**Comment by bago** [comment]
You did some syntax error in your html (I see a ";" after double quote in both code you quoted and it is not there in the template code.

**Comment by nabenzine** [comment]
I have replaced again template-versafix-1.html and template-versafix-1.model.json with the original ones from github and changed only <span to <div and it's the same issue

**Comment by bago** [comment]
The issue is unrelated to the title or the changes to versafix. This is something related to tinymce disposal and I'm not aware of "collateral damages" bug that console errors. You can see the same issue if you are editing the text part and you remove the content while the tinymce toolbar is visible (even with a default template).

So, if you see "collateral damages" related to that error please try to explain them so I can reproduce.

I left the console.error in place because it could help finding weird bugs, if they happens.
