### ISSUE TITLE
how to configure mosaico with the windows iis server

### ISSUE THREAD

**Issue by harshwardhanbsc** [voidlabs/mosaico#207]
how to configure mosaico with the windows iis server

please share the steps and needed things to install on the server

**Comment by bago** [comment]
Your question is out of scope for this project. 

Unless other users will ever share/contribute code to make it easier to deploy on IIS then I'll include it.

In the mean time your option is to read the documentation and develop your own backend code depending on the language you use in IIS. Otherwise look for a generic guide on how to integrate node.js with IIS.

https://github.com/voidlabs/mosaico/wiki/Serving-Mosaico
