### ISSUE TITLE
how to load a default template in the right panel

### ISSUE THREAD

**Issue by harshwardhanbsc** [voidlabs/mosaico#209]
How to load a default template in right panel on the page load.

**Comment by bago** [comment]
You have many options...

I would look at "src\js\ext\localstorage.js " to see how "save" to local storage works.

Then I would prepare a template and save it.

Then I would have a look at the localstorage content (via browser console).

Then I would change the  "viewModel.newEdit = " function in the index.html so to create a "non-empty" model and instead start editing with the model I previously copied from the local storage.


Otherwise you could write a "viewmodel plugin" (see the wiki) and iterate throught the "viewModel.blockDefs" and add each defined block to the viewModel.content().mainBlocks() array of contents.

**Comment by harshwardhanbsc** [comment]
can you share the wiki website url

**Comment by bago** [comment]
If you can't find the "mosaico wiki" on your own then you won't be able to complete the task ;-) Sorry but developing a plugin is harder than doing a google search or looking at the menu voices in this page.
