### ISSUE TITLE
Cannot apply backend image resizing to non-local resources - why?

### ISSUE THREAD

**Issue by cen1** [voidlabs/mosaico#210]
Function convertedUrl on line 31 in app.js specifically checks whether backendUrl is same as image src URL  and displays an error and behaves very badly if that is not the case. In my case it calls http://imageUrl.png?method=resize... which is completely wrong. I have images stored on s3 so the image links are different from backend URL but I don't see why this is a bad thing or wrong in any way. My backend simply retreives the image from S3, resizes it and returns it to mosaico. Why does this check exist? After removing it everything works flawlessly.

**Comment by bago** [comment]
I don't get your issue. Mosaico expect resources to be local. So it is not important how we deal with non-local resources. THe mosaico backend is not expected to be able to retrieve remote resources, so the client works according to this.

If you extend Mosaico to use remote resources then you have to deal with them everywhere.. You will have to alter your backend so to be able to resize remote images and serve them locally or something like this.. so altering also the convertedUrl function will be easy (it can be done in a plugin).

Mosaico is not meant to work with remote resources. You can add your own logic to allow this but in order to be "general purpose" this will have to deal with:

- an UI to let people upload OR use remote images
- a backend that will be able to resize "remote images"

For both of them you will have to change mosaico source code. So the convertedUrl method is the last of your issues, given it can be easily changed in a plugin (or directly in the mosaico code).

.. So.. if this is a "bug report" then this will be closed as "won't fix".
If this is a "feature request" then I'm happy to accept pull requests but I don't think it will be high priority.

If you want to know how to alter the url converter:
```javascript
var plugin = function(vm) {
  ko.bindingHandlers.wysiwygSrc.convertedUrl = function(src, method, width, height) {
    return yourownurlmadehow you like;
  }
};

Mosaico.init(blabla, [plugin]);
```

**Comment by cen1** [comment]
It was not really a bug report or a feature request, just a question really. Since the resulting mosaico HTML templates could be used for mass emails, lets say million people, serving the images from the same server as mosaico seems like a bad idea. Which is why I decided to make a custom backend that stores images remotely on a dedicated storage. This triggered the weird behaviour with `convertedUrl` which I mentioned above but other than that mosaico works fine, since it get's served proper images by the backend and remote nature of the images is hidden from the client.
The issue that remains is that the final HTML template has backend URLs for img src which means the final HTML would have to be parsed one more time, find the image tags, resize them, store them remotely and use the remote links instead.

The way mosaico interacts with backend at the moment, I am not sure there is anything that can really be done about this.

**Comment by bago** [comment]
Yes, my suggestion is to "post-process" them: at the end of the editing, before you send it, upload the images to S3 and replace the URLs in the message (PS: it is not a good idea to have S3 or CDN urls in the IMG SRC because of antispam reasons.. but you can use them if you use custom domains).

This is what most users do in their backends... this is something that is automatically done by some "email sending services" that will grab images and deploy them in their own CDN before sending a massive email... so we thought Mosaico can simply deal with local images because it is an email editor and not a tool to send massive emails.

Hope this helps.

**Comment by cen1** [comment]
Yes, that makes sense. I guess one difference with mosaico would be that it already expects properly sized images intead of resizing them via CSS but that's just an implementation detail.

Anyway, my original question was why `convertedUrl` checks for local resource and since this is clear now I am closing this.

Thanks
