### ISSUE TITLE
Instantiate multiple Mosaico instances in a single page

### ISSUE THREAD

**Issue by yannickv** [voidlabs/mosaico#222]
Hi,

I am working in a multi lingual environment and I am trying to instantiate several Mosaico editors (one per language) in a single HTML form visually split by tabs.
The first instance is working well, but the next instances seem linked to this first one and a bit buggy.
For example, TinyMCE editor will only appear for the first instance and the layout (set of blocks and inner configuration of blocks) of the emails is shared between all instances.

Do you know if Mosaico is designed to work with multi instances or if there is a known limitation about it?

PS: your tool rocks with a single instance!

**Comment by bago** [comment]
Mosaico is designed to use a full frame/window on its own... 
Use iFrames ;-)

**Comment by yannickv** [comment]
Many thanks Bago: this is quite clear.
I just wanted to be sure that I was not missing a hidden parameter.
Then I will change my design for iFrames.

**Comment by bago** [comment]
For the record I guess mosaico "could" work with multiple instances, but I don't think it worth improving it in order to support that scenario (e.g: Mosaico "disposal" code exists, but has never been used nor "exposed"). Mosaico is a full application itself, unline TinyMCE that is a simple "editor" that adds a floating toolbar to your content.
