### ISSUE TITLE
Client side image resizing: document how to change settings, issue with gif being converted to png

### ISSUE THREAD

**Issue by bubenkoff** [voidlabs/mosaico#223]
I noticed that for example gif file of a size of a 3MB when uploaded, gets converted to a smaller png file somehow.
But can't find it where are the conversion settings?
Thanks!

**Comment by Hiswe** [comment]
@bubenkoff Uploading/resizing is done server side

If you are using Mosaico's provided backend, you can find the resizing code here:

https://github.com/voidlabs/mosaico/blob/master/backend/main.js#L74-L112

**Comment by bubenkoff** [comment]
@Hiswe well, try to upload the gif like i mentioned, and check your browser network communication to see that instead of gif, server backend actually receives resized png instead. check `src/js/bindings/fileupload.js` as well
```
ko.utils.extend(options, {
      url: '/upload/',
      dataType: 'json',
      dropZone: $parent.find('.mo-uploadzone')[0],
      autoUpload: true,
      acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
      maxFileSize: 10 * 1024 * 1024,
...
```

so default max dimentions for images are (from `jquery.fileupload-image.js`):
```
           imageMaxWidth: 1920,
           imageMaxHeight: 1080,
```
if any of dimension is bigger, image will be resized client-side, and for gifs, apparently, resize also includes conversion to png

**Comment by Hiswe** [comment]
@bubenkoff I tried with a 17mo gif, and upload wasn't possible: it just shows me an error message.

Also tested with a 3000x3000 1.2mo jpg, and in this case file was uploaded correctly

Fileupload can be configured by [setting fileupload option](https://github.com/voidlabs/mosaico/blob/master/editor.html#L44-L47)

I hope it helps :)

**Comment by bubenkoff** [comment]
but try 3000x3000 gif, you'll get png instead

**Comment by bubenkoff** [comment]
the issue is, if big gif is animated, then it becomes static

**Comment by Hiswe** [comment]
If you provide the `gif` I will give a try :)

The only problem that I had encountered with gif so far was that resizing weren't done on all frame.
In the backend I just had to add the [.coalesce()](http://stackoverflow.com/questions/12293832/problems-when-resizing-cinemagraphs-animated-gifs) method call

**Comment by Hiswe** [comment]
@bubenkoff yep, just tried with a [big gif](http://oakley-graphics.wikispaces.com/file/view/zara-cartoon-animation.gif/310809716/640x386/zara-cartoon-animation.gif) same issue… strange

**Comment by bubenkoff** [comment]
needs a documentation at least
it's a very nice feature that resizing is there, client side, as then there's nothing left for the backed except the storage

**Comment by bubenkoff** [comment]
https://s-media-cache-ak0.pinimg.com/originals/b1/5f/97/b15f97463be2583c0db7f9b8df8c84fd.gif for example

**Comment by Hiswe** [comment]
@bubenkoff yep for the strange `fileupload` behaviour. 
In my opinion this `gif => png conversion`  is not related to mosaico but related to [jQuery-File-Upload](https://github.com/blueimp/jQuery-File-Upload)

For the resizing, if you have always access to the original file, why not.
You should be able to override the `ko.bindingHandlers.fileupload` behaviour by making a [plugin](https://github.com/voidlabs/mosaico/blob/master/editor.html#L39) I think…

**Comment by bubenkoff** [comment]
true it's not directly mosaico issue, but that plugin is used

**Comment by bago** [comment]
Please note that this may span multiple layers:
We have a client side resizing made by jQueryFileUpload ( @Hiswe already gave you pointers)
The we make an upload to the backend and the backend may have "file upload" maximum size limits (e.g: php by default have a 2MB limit, or something similar): this depend on the specific technology used by the webserver.
Then you have a backend implementation that will do the image manipulation (cut/cover/resize of the image): depending on the image manipulation library you may experience different results. E.g: most image manipulation libraries don't account for GIF animations so Animated GIFs are broken: each placeholder gives you a "real size", so you can simply upload an animated gif of the correct size and the backend could be able to "understand this" and avoid manipulation (our proprietary backend on mosaico.io does this, I can't tell you how the node.js demo backend or the opensource php backend deal with this because I never checked).

**Comment by bago** [comment]
About the need to better document this behaviour please provide a PR with the documentation you think will help others in future (most people doesn't even read the main readme so I'm not so inclined to document each and every behaviour when the time needed to find the right document is similar to the time needed to inspect the code).

**Comment by bubenkoff** [comment]
@bago thanks, i'll try to come up with a pull request

**Comment by perlpty** [comment]
I just saw this threat, and I would like to comment some lines since I faced a similar issue when developing my backend. 

I have to say that besides the problem with gif --> png conversion there are other issues that might arise from client-side resizing.  One different issue that happened to me while testing was that some big jpg images (more than 1080H that where being resizing twice: client-side + server-side) with blue sky and some clouds were being uploaded with a partially green sky due to client-resizing.  After reading a lot I found that client resizing is automatic of those big images (see:  [Client side Image Resizing](https://github.com/blueimp/jQuery-File-Upload/wiki/Client-side-Image-Resizing)  )  

I really thanks the author for exposing this JQuery-File-Uploads configs in the editor.html.

So I decided that It would be better to just turn off auto resizing by doing this:
`disableImageResize: true, maxFileSize: 10000000,	// 10 MB`

If you still need to do client resizing but with different default limits, just do that instead:
`// imageMaxWidth: 1920, imageMaxHeight: 1080,  // use different defaults`

**Comment by bago** [comment]
I close this one. PR with documentations improvements are welcome!

**Comment by selecta-ufuk** [comment]
> If you provide the `gif` I will give a try :)
> 
> The only problem that I had encountered with gif so far was that resizing weren't done on all frame. In the backend I just had to add the [.coalesce()](http://stackoverflow.com/questions/12293832/problems-when-resizing-cinemagraphs-animated-gifs) method call and it solved my issue.

I know it's a very old topic, but where and how did you install it? I'm facing the same problem and think you had the solution back then. thx
