### ISSUE TITLE
templating - image source vs image upload

### ISSUE THREAD

**Issue by perlpty** [voidlabs/mosaico#234]
Hi.

How could I upload a picture but using as placeholder (or default image)  the image in template?  I took a look at "versafix-1" template as guidance, but I couldn't find what I was looking for.

I have not found a working solution to this yet.  All I have is 2 options (see below) but Im looking for mix of them.

 **(1) Image source editing showing template image**
![image_source](https://cloud.githubusercontent.com/assets/23323762/20221146/37890b14-a7fe-11e6-96ad-d641f13f1211.png)

HEADER

`@supports -ko-blockdefs {`
`      src { label: Image; widget: src; }`
`      url { label: Link; widget: url; }`
`      alt { label: Text Alternative; widget: text;`
`      }`

` HEADERBlock logoImage { label: Logo Image; properties: visible=true src url alt;}`
`}`

HTML Uses: **-ko-attr-src: @logoImage.src;** 
`<img src="img/_logo.png" alt="logo" style="-ko-attr-src: @logoImage.src;  -ko-attr-alt: @logoImage.alt;  display:block; line-height:0px; font-size:0px; border:0px;"    width="148" height="48"  border="0" />`

|
|

  or **(2)Image Uploading by using mosaico place holders.**
![image_upload](https://cloud.githubusercontent.com/assets/23323762/20221155/3e017e68-a7fe-11e6-9796-8e77ee681596.png)

HTML Uses:  **data-ko-editable="logoImage.src"** 
`<img data-ko-editable="logoImage.src" src="img/_logo.png" alt="logo" style="-ko-attr-alt: @logoImage.alt;  display:block; line-height:0px; font-size:0px; border:0px;"    width="148" height="48"  border="0" />`

Both ways works, no issue on that.  However, I would like to render the template image as default image, **in case, someone would like to use the template image without alteration in his email.**

Is that possible?

Thanks.

PD:
BTW, I have read:
1. https://github.com/voidlabs/mosaico/wiki/Template-language
2. https://github.com/voidlabs/mosaico/tree/master/templates/tutorial
3. versafix-1 & tedc15 templates

**Comment by bago** [comment]
Try adding a data-ko-placeholder-src="path" to your img tags in addition to the src="path" attribute.
If this works like you expected, please answer here documenting the way you did it.

**Comment by perlpty** [comment]
Ok... I will try to check this tomorrow and report it back.

**Comment by bago** [comment]
Did you test? Please report back!

**Comment by perlpty** [comment]
Sorry for delay.  Preliminary (draft) report is: It might be working.  From what I see:
1) Image source appears to be from the template image and not from place-holder.
2) If I delete that image, Then I get the option to upload a new image.

However, In my case I have not seen it fully working since my templates are in a different path, which were working with a .htaccess hack until this report. And also, I made my own backend based on php-backend.  And in that back-end For /img command it was expected to make an image resize from an source image in Upload folder.  But, since it is a template image, the image source folder should be changed to the template folder instead.

Later, I will ask in the forum how to move the templates in a "Mosaico way" and not by hacking.

So, before fully see that working, I need to rewrite my back-end to take into account the new template folder for /img command, and possible change the .htaccess file.  Until then, I wont be able to see it fully working.  Hopefully that will happen today or tomorrow.

**Comment by perlpty** [comment]
OK.  Now I can confirm: It works!  but not the way I expected to be.

**WAY OF WORKING:**
It works like described above:

1. Image source is from the template folder and not a dynamic place-holder.
 2. If I delete that image, Then I get the option to upload a new image.

**EXPECTED WAY:**
I 'd have expected to behave like this:
1. Image source is from template folder --> That 's expected and this step works as described.
2. Get the option to upload a new image without deleting it first. 

So, It works with a very little difference (step 2).  However, I think the author might has reasons in his code to do it in this way and not the way expected.  So, It 's ok for me.


**My Implementation:**
`<img data-ko-editable="logoImage.src"  data-ko-placeholder-src="img/_logo.png" src="img/_logo.png" alt="logo" style="-ko-attr-alt: @logoImage.alt;  display:block; line-height:0px; font-size:0px; border:0px;"    width="148" height="48"  border="0" />`

NOTES
I dont know how the node-backend would deal with the different source image paths ( template path vs upload path ), but for anyone who has another backend, care should be taking when resizing in response to IMG/ command.  Even more if templates are not in normal location.

**Comment by perlpty** [comment]
I just found another post with same isuee/solution (data-ko-placeholder-src="placeholderpath").  Just for reference:
  #211

**Comment by bago** [comment]
I don't like the idea of "custom placeholders": placeholders currently are a "backend things" and are used to say "here there is no image, but you have to add one". "Default values" for images are a different things, and if you want to replace an image you first trash it and then upload a new one over the placeholder.

Now, i understand the issue with image paths that may not be handled correctly by the backend, but I don't see a "good solution" to this issue... 

At this time the content of "data-ko-placeholder-src" is ignored but when this attribute is present then the "src" value will be used as a real value for the image. But, "src" path will probably be a resized/cropped version of the original image.. so maybe we should use a "data-ko-image-src" with a pointer to the "full size image" and use this one as the "value" when this attribute is used... Also, this "data-ko-image-src" could be "relative" to the upload folder and not the template path...

I don't know .. i don't see a "straightforward" solution to this issue. For sure I see a "weird difference" between how we deal with texts and how we deal with images: text from template is used as the "value" while src for images are not used at all. While this "hurt" me "logically", it worked very well with our users.

Please note that "data-ko-placeholder-*" attributes are not documented because we consider it "experimental" and we are still trying to understand what is the best solution.

One thing to take into consideration is that the "placeholder" (or the default value) will have to be handled by the resize/cover manipulation because you can often change image size/aspect ratio even when you are looking at a "placeholder" or a "default value".

About your use case: is your "default value" a custom placeholder (just to make a better placeholder) or a real image that you expect your user to "send" ?

**Comment by perlpty** [comment]
In my use case, this image would be a real image that I expect to be used.
