### ISSUE TITLE
MoxieManager

### ISSUE THREAD

**Issue by pkasar** [voidlabs/mosaico#284]
Do we get MoxieManager for free when we use commercial version of Mosaico?
we plan to use Mosaico in our .net application
Thanks

**Comment by bago** [comment]
No, moxiemanager is just implemented in our demo.

Using the GPL version of mosaico you can't link to moxiemanager due to licensing incompatibility.
Using commercial version of mosaico you can link to it, but you have to buy its license on your own.

BTW for commercial version questions feel free to write to the info at mosaico io email address.
