### ISSUE TITLE
How Download Button Works

### ISSUE THREAD

**Issue by kbalajijan1** [voidlabs/mosaico#30]
Awesome work! Thanks for sharing your code. It works fine in my localhost.

May I know where the codes for download button has been written
 
I can see the proper template structure in the downloaded html file which is working fine even in Outlook, Have you used any parser to build this email template.
 
I would like to store this template to my server and re-load the saved template to the editor again.

It would be very helpful if you give some brief about this

Thanks,
Balaji. K

**Comment by bago** [comment]
The button is added to the interface by the "localstorage" plugin: 
https://github.com/voidlabs/mosaico/blob/master/src/js/ext/localstorage.js#L65
```
   viewModel.exportHTMLtoTextarea('#downloadHtmlTextarea');
   var postUrl = emailProcessorBackend ? emailProcessorBackend : '/dl/';
   global.document.getElementById('downloadForm').setAttribute("action", postUrl);
   global.document.getElementById('downloadForm').submit();
```
This invokes a method to export the HTML to a textarea and the submit form including that textarea so that the backend will receive the HTML content.
viewModel.exportHTMLtoTextarea is here:
https://github.com/voidlabs/mosaico/blob/master/src/js/viewmodel.js#L423
The export process creates an iframe, renders the template there and then cleanup the content from knockout directives (and a bit more).

The backend here:
https://github.com/voidlabs/mosaico/blob/master/backend/main.js#L111
deals with the "/dl" form POST, run a CSS inliner on the content and then send it back to the client.

- CSS inlining could be done on the client (I had no time to implent it on mosaico library and it was easier to do that on the server)
- The download needs a client-server communication because some browser is not happy to artificially create a download from clientside data (safari).


About save/load keep in mind that the HTML is not the content you are editing. Your "editable object" is a javascript sructure and the HTML is just an "export" of your project that cannot be "imported".

So, if you want to save/load you have to deal with:
https://github.com/voidlabs/mosaico/blob/master/src/js/viewmodel.js#L474
viewModel.exportJSON and viewModel.importJSON are the methods to save/load the content for your current template
viewModel.exportMetadata instead exports some metadata about it (e.g: the template you are using).
the metadata cannot be imported but you can pass metadata to the Mosaico.init method as the "options->data->metadata" key:
https://github.com/voidlabs/mosaico/blob/master/src/js/app.js#L88
In the init you can also pass the content json in the "options->data->content" key.

So, if you need a save/load then you will have to look at the "saveCmd" in localstorage: you push the metadata+content json to your server and then to start working again you start mosaico.init with metadata+content.
If you instead want your user to be able to download/upload their workinprogress you will have to let them download this metadata+content objects and then implement an initialization method to start mosaico from the upload of this metadata+content.

Of course contributions are welcome ;-)

**Comment by kbalajijan1** [comment]
Thank you for detailed explanation. Let me try.

I will reopen this ticket if I face any issues.

Thanks,
Balaji. K
