### ISSUE TITLE
PHP back end nearly complete - have some questions

### ISSUE THREAD

**Issue by mherbold** [voidlabs/mosaico#31]
I've done about 80% of the PHP back end yesterday.  I am more than happy to share the code.  But to complete the back end I have some questions and comments:

1) There is apparently no way to delete uploaded images.  I am not sure if I am just missing something in my back end, or if this ability is truly missing from Mosaico.  As far as I can tell, the only way to delete images is to SSH / FTP to the uploads folder and delete them manually.  For the fileupload.js JSON response I am not returning the delete_url and delete_type field / values.  Could this be why?  I looked in the main.js reference and listFiles function is not returning those either which is why I did not bother.

2) I had to make some modifications in editor.html to the following starting around line 31:

var webpath = window.location.href.substr(0, window.location.href.lastIndexOf('/'));
  var ok = Mosaico.init({
    imgProcessorBackend: webpath + '/img',
    emailProcessorBackend: webpath + '/dl/',
    titleToken: "MOSAICO Responsive Email Designer",
    fileuploadConfig: {
      url: webpath + '/upload/',
      // messages??
    }
  });

The differences are: (a) doing a full url instead of a relative url because when downloading the email the relative urls are used as img src parameters, which means images will be broken if viewed on a different website or in an email client.  Also by doing this, we make Mosaico able to work in subfolders instead of requiring it to be at the root of the domain.  And (b) I added a trailing forward slash to /dl/ and /upload/ because without the forward slash at the end some web servers will do a 301 redirect to add the forward slash and this causes post data to be lost because Mosaico will redirect using a get instead of retrying the post.

3) For the /img back end function I have the 'placeholder' and 'resize' coded.  I cannot seem to find a use case for the 'cover' path.  Can you tell me how I can make Mosaico request the 'cover' method so I can finish this part in the PHP back end?

4) Also regarding the /img back end function - The 'resize' method function seems to be used directly inside the downloaded html email.  This means if I send this out to 1 million people, my server will be overloaded with 1 million+ resize requests.  There should be some caching system similar to thumbnails in Mosaico - for example creating a /uploads/resized/ path and storing resized images in there with file names like width_x_height_filename and then storing the direct url to those resized images when downloading the html emails.  My server's CPU will thank you.  :-)

5) I have not done the 'email' path for the /dl function  yet.  This and the 'cover' path for /img are the only remaining things to code for the PHP back end that I have, and it is complete.  The PHP back end is just 3 files and does not have any dependencies other than requiring Imagemagick for PHP to be installed.  Can you tell me what the best way is to share this with you?

**Comment by bago** [comment]
1) You are right. Mosaico at this time does not have anything to delete files. Of course this could be added, but in our application we have an external file manager (moxiemanager) so we didn't need deletes from mosaico.

2) editor.html is not part of mosaico library: you can use it as a sample, but you should simply host in your web application as you like. So, the sample editor.html uses hardcoded paths because it is expected to deal with the sample node.js backend that is on that specific path.

3) "cover" is used when the img placeholder declare both sizes. in versafix-1 this happen in blocks having multiple images in multiple columns (either the 2-3 article in columns blocks or the 2-3 images blocks).

4) In our own implementation we postprocess any email and create static copies of each image before we send. Otherwise you can add caching, maybe a simple varnish will do the trick.

5) That's cool! Maybe you should create your own github project so you can easily update it: I will link to your product: I think many will be happy for this, because we received many questions about serving mosaico from apache/php!

**Comment by mherbold** [comment]
Perfect - with your answers I should be able to complete the PHP back end very soon.  I will also add post-processing to the /dl function to create static resize / cover images mgically "behind the scenes" as well.

**Comment by mherbold** [comment]
I am running your demo Mosaico vs mine side-by-side and comparing to find differences.

1) The font size in your placeholder image seems to be scaled proportionally to the image size in your demo.  In mine it is fixed at 20 points because that's what it seems to be doing in main.js.  Hmm.

2) When going to Gallery and clicking on the Gallery tab and when we don't have any uploaded images, yours goes "Loading gallery..." then "No images uploaded, yet.".  Mine goes "Loading gallery..." then it goes blank.  I am returning an empty array for "files" which is what it seems to be doing in main.js.  Not sure what is different.

Those two are the only differences that I can see so far.

**Comment by bago** [comment]
1) our demo on mosaico.io uses a "proprietary" backend written in PHP: I'm not the author in this case but I think the font size adapt itself to the image size. BTW: you can implement it as you like, it is not a "key feature" for the editor. The node.js implementation gives different results depending on imagemagick (IIRC in my windows it doesn't take external TTF, while the php version is able to use external fonts).

2) This sounds correct. Please reload your mosaico page when you test (once it fails some ajax call it may remember stale results).

**Comment by mherbold** [comment]
Well the good news is that I have completed the PHP back end.  I finished the 'cover' and the 'email' functions.  It all works.  I have not done the post-processing to create static re-sized images yet.  I wanted to get the PHP back end working as-is first, which it is now.  Next I am going to create my Github project (my very first!) and upload my files.

However, when I sent my test email and looked at it in Outlook I was disappointed to find that it's not displaying as cleanly as I hoped.  I am using Outlook 365 (2016) and there's some glitches in the HTML display.

How it looks in Mosaico - just a block with the 534x200 image followed by a block with the 166x130 image:
![in mosaico](https://cloud.githubusercontent.com/assets/521887/11001449/7efdda06-8464-11e5-8c6a-dd561186cc07.PNG)

This is how it displays in Outlook:
![in outlook](https://cloud.githubusercontent.com/assets/521887/11001583/0fdd74aa-8465-11e5-837d-cbd50b5f0cef.PNG)

And when you click on the gray area to the left, it becomes this in Outlook:
![in outlook after click](https://cloud.githubusercontent.com/assets/521887/11001630/64b5601e-8465-11e5-96e1-9678ff475736.PNG)

Weird.

**Comment by mherbold** [comment]
Interestingly enough, if I create the exact same email using your demo site at mosaico.io and send myself a test email, it displays correctly.  The separation between blocks when clicking on the gray area (image 3 above) is still a problem, but the issue shown by image 2 is not present.  I'm guessing something was fixed / updated in Mosaico that isn't available to us yet through github?

**Comment by mherbold** [comment]
OK I created a project on Github and here it is: https://github.com/ainterpreting/mosaico-php-backend

I hope I did OK.

I'm now going to begin work on the post-processing of the html email (create static resized images, fix links, etc.)

**Comment by bago** [comment]
Please note that the "dl" backend DOES "css inlining" and that is may be very important: mosaico.io uses a proprietary php backend, so the main difference is the inlining. the github version uses the nodejs backend with a nodejs inliner. The version you forked uses your own backend that DOES NOT do inlining.

mosaico.io uses the same very template version of github: in fact I work on github and then I update the templates for mosaico.io from github.

The differences between mosaico.io and github version are explained in the main Readme of the project (moxiemanager, different backend, the onboarding, right click contextual menu)..

**Comment by mherbold** [comment]
AHA!  So that is what that Styliner thing was.  I wasn't sure what it did.  :-)

Now that said - your version still has the weird "separate on click" glitch.  When you have the 534x200 block above the 166x130 block and send the test email, when in Outlook 2016 you click on the gray area to the left of the blocks, the blocks separate.  When you click elsewhere, the blocks pop back together.  Weird.

**Comment by mherbold** [comment]
Tah-dah!  I added Premailer support for the css inlining.  I checked the output in Outlook and the CSS issues shown in image 2 are fixed.  Thanks for your help!  Now we are really close to complete.

**Comment by mherbold** [comment]
I added a post process (in /dl) to convert resized images into static images before emailing or downloading.  My job is done.

*drops microphone*

:-)

**Comment by bwl21** [comment]
You could use  https://github.com/tijsverkoyen/CssToInlineStyles to remove the dependendency in premasiler service.

**Comment by bago** [comment]
In the mid/long term I'd like to move inlining on the client side, in the main mosaico library. It makes no much sense to do that on the backend as we already have support/tecnnologies and we already parse CSS on the client side, anyway.

This way the resulting email would be the same on every environment and not depending on the backend implementation.

The inliner is an "important" part of the process because it is hard to do the right inline thing and the resulting email may work or not on specific clients because of how you inlined it.

We didn't put the inliner in Mosaico because we already had a backend with a working inliner used for email created with our previous editor, so we didn't need that specific feature in the client.

The best solution would be one leveraging mensch (css parser in js) we already use for the other css parsing in mosaico, so to not introduce more dependencies...

But, I don't know when I will find some time for that.. so, this was just to share what the original plan was.
