### ISSUE TITLE
Help for installing

### ISSUE THREAD

**Issue by amariussi** [voidlabs/mosaico#321]
Thank you for sharing Mosaico.
I have read everything (even more than three times as suggested) but, unfortunately I am still not able to install a working copy of mosaico.io.
This is a shame because it is a very nice and useful application.

My first try is on a Windows machine running WAMPServer.

First I managed to install nodejs* sucessfully.

Then I ran "npm install -g grunt-cli" followedby "grunt" and the output was the following (error):
![grunt_error](https://cloud.githubusercontent.com/assets/8026129/25431061/49e31c56-2a7f-11e7-9fdd-d22f7ed68c9b.jpg)

I then tried "npm install" followed by "grunt" and again "npm install" and after all the procedure was over I got a few more errors:
![2017-04-26_130210](https://cloud.githubusercontent.com/assets/8026129/25431394/ba445658-2a80-11e7-9c15-f146b5ed9ea6.jpg)

From the messages I understand that many things went wrong and I am definitely missing a number of components that need to be installed prior to Mosaico.

Unfortunately the installation procedure doesn't provide sufficient instruction for who is completely not familiar with these components.
I am not asking for a detailed step by step installation procedure, but at least a (complete) bullet list of the required components (possibly with the places where to get them).

I assume that I may not be the only one not managing this installation because of the lack of experience with this type of components.

I hope you will be able to help!

Thank you!!!

**Comment by Hiswe** [comment]
@amariussi The error log tells that bower can't find git.
Do you have git installed on your computer?

**Comment by amariussi** [comment]
Thanks for the Quiock reply.

I have now installed git and then I have run a new cmd window.

I went to the mosaico directory and I have run grunt. This started a long procedure (no errors) but it stopped at: "running watch task (waiting...)":
![2017-04-26_133258](https://cloud.githubusercontent.com/assets/8026129/25432481/ed8c2adc-2a84-11e7-89b2-da7a0b47dd30.jpg)

Since this was taking too long I tried opening a browser tab at 127.0.0.1:9006.

Now Mosaico shows up. So I selected the first template on the left. But when I add any of the blocks the result seems to be broken:
![2017-04-26_133550](https://cloud.githubusercontent.com/assets/8026129/25432588/50f128a2-2a85-11e7-9043-59388547e2fd.jpg)

Additionally some parts don't seem to be editable (for example the icon at the bottom specifyin that the email is being sent via VoxMail:
![2017-04-26_133745](https://cloud.githubusercontent.com/assets/8026129/25432672/b1057a18-2a85-11e7-99f6-9d3bdf259ecc.jpg)

It's OK if it says created by Mosaico, but why VoxMail? ANd in Italian?

Apart fom this last point I am still probably missing something I assume.

**Comment by Hiswe** [comment]
- `running watch task (waiting...)` is expected: the server is running
- for the broken images, I guess it's because you don't have `imagemagick` installed on your computer
- depending on the template, some parts are not editable. That's the way the template are build: making editable and not editable parts.
- *voxmail* is part of the italian based company *voidlabs*, which maintains mosaico

**Comment by amariussi** [comment]
I have now installed imageMagick but I am still getting broken images.

I also restarted everything and re run npm install as well as grunt.

I checked the Chrome console and these are the messages:
![2017-04-26_141838](https://cloud.githubusercontent.com/assets/8026129/25434171/943376c8-2a8b-11e7-9c2a-eb282a6d32aa.jpg)

**Comment by Hiswe** [comment]
Nothing wrong with the log.
The warn is only a warn.
Without a block with placeholder images those logs are ok.

You should dig in the dev server code to see what happen.

**Comment by amariussi** [comment]
OK, thanks.
I will look at other logs to try to understand what happened and post back here.

**Comment by amariussi** [comment]
After one day of trial and error unfortunately I am still unable to get it to work.

In addition to the broken blocks with images I have also found that, if I try to export the draft template I get an error message screen:
![2017-04-28_155052](https://cloud.githubusercontent.com/assets/8026129/25531564/7f332e3a-2c2a-11e7-8993-4bd6598cbf3b.jpg)

I found some error messages in one of the logs: towards the end of the log (see attachment) there is a sentence that attributes the issue to Mosaico, but I am completely unable to establish if that is the case.
It surely is due for some lack of information on the installation procedure.
![2017-04-28_155813](https://cloud.githubusercontent.com/assets/8026129/25531891/895dd9d6-2c2b-11e7-8f1f-43992316f768.jpg)


Here is the log:

[2017-04-26T09_50_05_421Z-debug.log.txt](https://github.com/voidlabs/mosaico/files/964506/2017-04-26T09_50_05_421Z-debug.log.txt)

**Comment by bago** [comment]
The error you report in the last comment is something totally different from your first comment.
In your first comment you succesfully built mosaico, otherwise you couldn't have created that screenshot.
In your last comment you are failing to build mosaico because bower is not able to run.

I can't know what you did between the two.

Start from scratch and follow the readme.

**Comment by amariussi** [comment]
I did nothing in between and it's a fact that, in addition to the error messages it is not working properly.

I posted two errors:
. one is about something not working when I tried to download an edited email
. the other one says that something failed in the install

Additionally, in my previous post, posted other installation errors and other application errors.

How do I uninstall in order to restart scratch?

The read me is for those who know. How about those who don't?

It's a pity because with just a few clear lines of bullet points with:
. full list of prerequired packages (specifying where to get them)
. full ordered list of commands to issue

The current read me is too vague for someone who is not familiar with these components.
Sorry if I keep asking for help but I would really want to install it. I am using SuiteCRM which have announced that they will adopt your solution (or at least part of it) so I want to be able to use it.

Thanks!

**Comment by bago** [comment]
I'm sorry if it is not documented/easier enough. At this time this is the state. 
Contributions are welcome.

IMHO it is impossible that you did the first screenshot if bower doesn't work, so it worked at least once. Then the "Not found" error is something coming from Apache (AFAICT), so it means you are doing something else from "running the default mosaico test environment".

https://github.com/voidlabs/mosaico/blob/master/README.md
https://github.com/voidlabs/mosaico/blob/master/CONTRIBUTING.md
https://github.com/voidlabs/mosaico/wiki

I'm closing this issue because it mixes 2 different issues.
Make sure you read README and CONTRIBUTING before you open another issue. THank you.
