### ISSUE TITLE
Debug mode off

### ISSUE THREAD

**Issue by JbalTero** [voidlabs/mosaico#331]
Is there a way to disable the debug mode?

**Comment by bago** [comment]
What do you mean with "Debug mode"? There is an internal debug mode but it is disabled by default and you can enable it by exposing the viewModel and the calling viewmodel.setDebug(false).

But I guess this is not what you need.

If with "debug mode" you mean javascript console messages then there is no option to do that. You can search the code and comment "console" calls or you can override the console object with your own implementation not using the window console.

If your issue is the "javascriupt console output": what is the problem with it? Nowadays having console outputs in applications is very common (modern browsers hide them unless you enable developer mode).

**Comment by JbalTero** [comment]
Thanks

>If your issue is the "javascriupt console output": what is the problem with it? 
I just thought maybe  there's some variable flags I can set since there are debug comments.
