### ISSUE TITLE
Versafix : Outlook and gmail display issues

### ISSUE THREAD

**Issue by heavynounours** [voidlabs/mosaico#335]
Hi !

I think there is a little problem with Versafix template and Gmail/Outlook : I know these two are a pain in the a**, but my customers are pretty "upset" about it.

Gmail
====

In mobile mode, the raw HTML source (after sending it to the customers) handles well the "2 images" and "3 images" blocks. But with Gmail, they are completely destroyed : 

![Gmail responsive](https://img15.hostingpics.net/pics/260420Fid1PpjE5m.gif)

Gmail announced back in September 2016 they would support media queries ... So what is the problem ? There is some "hacks" who destroys everything now in Gmail ?

Outlook
======

Even in normal mode, the custom block I made (6 images in a row, based on "3 images" block and "2 images" block) is completely destroyed ... An idea ? (Outlook 2016 MSO 16.0.4498.1000)

![Outlook](http://taiga.naxxt.io/media/attachments/2/c/3/7/1df2c6f1c7c1aa63f172f1edfd4f7cd998f17989e705070e05ae01c06979/seg-outlook_2016-mso-16044981000.png)

**Comment by bago** [comment]
You opened an issue about versafix and half of your issue is about a "custom block".
I can't help on custom block. Creating html for email is a PITA.

1) Versafix has been created BEFORE gmail changed their way and "supported" MQ.
2) We think gmail support for MQ is wrong/buggy so we decided not to use it and only rely on "spongy" behaviour.

Versafix is one of the most compatible template you'll find on the web. But the only way is compromises: if you want to increase compatibility you have to accept it could not be the "best" on some platform.

We'll release an updated version of versafix soon, but we decided not to use MQ for Gmail, so this issue won't be fixed by versafix.

Mosaico doesn't force you on specific HTML, so if you know how to make a better template you can create it and then make it "editable" by mosaico.

**Comment by heavynounours** [comment]
Ok I understand for the custom block, no problem with that :)

But on the Gmail part, which guidelines should I follow to fix Versafix for gmail ?

Thanks by advance

**Comment by bago** [comment]
I'm sorry I don't think versafix needs to be FIXED for Gmail. The current behaviour is intended and in our opinion is a correct way to adapt to a narrow display when MQ are not supported (or not correctly supported).

I'm not the right person to ask for guidelines to fix something I decided it was not correctly fixable. Maybe someone else have found better solutions, but you will have to ask them. At the moment I think versafix is the best compromise out there if you care about client-compatibility.

You can find some "mobile-first" approaches that will reduce mobile issues at the expense of desktop issues. IMO in 2017 with the current email open distributions the versafix approach is better.

**Comment by heavynounours** [comment]
Ok.

Just in case, the media queries are ok, but are targeting on browser width, like normal media queries, not the "email view box" width.

**Comment by bago** [comment]
IMO they are not OK as they don't let you react to the email viewport size and you have no way to guess it and target it. IMO it was better the old Gmail.. now if you have "good MQ" you could have bad results on Gmail: I prefer a client that does not support a feature to a client that does support a feature but with a different behaviour from what is expected. The could just simply use an iframe and make better use of browser security features this way, too.
