### ISSUE TITLE
Images not showing when test email is sent.

### ISSUE THREAD

**Issue by DanyalS** [voidlabs/mosaico#337]
When i send a test email to my gmail account, the images i upload by drag/drop or when i link them, do not show up in the email. Everything else seems to be working fine but for images im getting the broken image icon.

**Comment by Hiswe** [comment]
Are you sending this from the local test server or by running it hosted on
a server ?

On Jun 27, 2017 20:36, "dany" <notifications@github.com> wrote:

When i send a test email to my gmail account, the images i upload by
drag/drop or when i link them, do not show up in the email. Everything else
seems to be working fine but for images im getting the broken image icon.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/voidlabs/mosaico/issues/337>, or mute the thread

**Comment by DanyalS** [comment]
Im running it locally(http://localhost:9006) using Grunt. Is that the problem?

**Comment by Hiswe** [comment]
Internet can't access your localhost. So Gmail can't access the images you
have uploaded.

**Comment by DanyalS** [comment]
Yea silly me, makes sense.

**Comment by godara-ravi** [comment]
Hi,

I am facing the same issue. And here this is running it on a hosted server.

**Comment by godara-ravi** [comment]
@bago but i am not on localhost. I am on hosted server.

**Comment by bago** [comment]
So, maybe you don't have the SAME issue. This issue here is about a "localhost" url not being visible from anyone else but the "localhost" user.

**Comment by godara-ravi** [comment]
Same issue means broken images are showing in gmail. And i using not localhost, am using my hosted server path. And from path images are images fine but in gmail these are not showing.

**Comment by godara-ravi** [comment]
There was global url issue with my backend. Now it resolved.
Maybe it will help someone:
If you are using mosaico and use your own backend and you are facing image broken issue in gmail. So, please make global image url so it would be accessible.
