### ISSUE TITLE
Image src editable with either URL or upload

### ISSUE THREAD

**Issue by rthouvenin** [voidlabs/mosaico#354]
I am trying to create a custom block that contains an image. From the versafix example, I understood how to make the image editable by uploading it (with src widget), or by letting the user provide an image URL (with the text widget). But I couldn't find a way to let the user decide whether they want to provide a URL or an image. Did I miss something?

The only thing I can think of is to add 2 images in the template (one with src widget and one with text widget), and they are displayed based on the value on an extra select box. But that sounds overly complicated.

Any better solution?

**Comment by bago** [comment]
Mosaico needs to have direct access to the images because the backend manipulate them "on the fly" according to the image editing widget.

So, if you want to use remote sources your best option is to create a panel where people write an url and some feature you add to mosaico (or the backend) download the image from that url and make it local. 

I never considered this an high priority: you can save the remote resource and upload it... it is just a couple of clic more than copying the src url.

**Comment by rthouvenin** [comment]
I understand, I had not realised that the backend manipulation is something that's required.
In my case, the images are actually on the same server (an existing repository in drupal, while mosaico is [CiviCRM's extension](https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico), in the same drupal instance), so I'll see if I can set-up the whole thing in a way that mosaico can access drupal's files.

**Comment by filiphanes** [comment]
Hi, I would like to edit src for images without backend manipulation. How could I do that, please?

**Comment by lanredestiny** [comment]
> instead of
> 
> `<img data-ko-editable="src" />`
> 
> use
> 
> `<img style="-ko-attr-src: @url" />`
> 
> This way mosaico will simply ask for an "url" property in the "Content" pane and use its value as source, without dealing with it in a special way like it does with "editable" images.

Whenever I use the but tags the template won't be visible anymore, what do you think is the problem.
[versafix-2.zip](https://github.com/voidlabs/mosaico/files/4885637/versafix-2.zip)
