### ISSUE TITLE
Can't append bold/italic text to a button/link in Chrome

### ISSUE THREAD

**Issue by chrispjay** [voidlabs/mosaico#362]
In Chrome when you are editing the text on a button or link, if you try to insert bold or italic text at the end or beginning nothing happens. To get it to work again you have to remove the styling of the text and sometimes delete a few characters. The same issue occurs if you select the text, make it bold and try to type at either the start or end of the text. Interestingly, this doesn't happen if you change the elements into <spans>. 

This issue occurs on the built in templates on master as well as several of the release versions of Mosaico using the bundled back-end. I also tested it on both of the templates in the "Try" section of the Mosaico home page.

The elements I had an issue were the buttons on the templates and the links at the top of versafix-1. All of which are <a> tags.

I tried the latest Chrome, Firefox and Microsoft Edge on Windows and Linux and only had the issue on Chrome in both OSes.

**Comment by bago** [comment]
Hi, I've been able to isolate the issue to TinyMCE and reproduce it on their fiddle with a very simple code:
http://fiddle.tinymce.com/rZfaab/1
Unfortunately this is not fixed in the latest release of tinymce.

This sounds similar to #151 or #212 . I've reported a few bugs against TinyMCE inline editing but they never answered to them (https://github.com/tinymce/tinymce/issues/3222 , https://github.com/tinymce/tinymce/issues/2146 )

**Comment by bago** [comment]
Tinymce seems to close issues after a while, with no sense, even if they acknowledged the bug and there is still a fiddle showing the issue. So this make reporting bugs a waste of time.

Btw, I filed a new one as I was investigating an issue and I had a ready fiddle:
https://github.com/tinymce/tinymce/issues/4299

Sounds like there are many issues with editing an "a" tag with tinymce (maybe the issues are in the contenteditable implementation from the browser, of course), maybe we should add a workaround like the one we do when declaring a "td" editable (in that case we add a div so to let the editor work fine)
