### ISSUE TITLE
when loading content from database, to the editor unable re-edit it ?

### ISSUE THREAD

**Issue by sibbu2005** [voidlabs/mosaico#381]
I can save the exported content and metadata, but when I am going to edit it again , I faild to load the editor controls . Like blocks are loading , I can see the content but I could not edit text, title etc. What I am missing?

here is my implementation :+1: 
https://gist.github.com/sibbu2005/be0b56a1873da569c0f0a60a249941c8

**Comment by bago** [comment]
I'm sorry I can't understand your issue and I can't see from the gist what you changed or anything.
You should be able to implement save/load with NO CHANGES to mosaico core code, so, don't break it ;-)

In order to load something from DB you have to pass the JS objects (metadata and content) in the Mosaico.init call: i don't see anything like that in you code.
https://github.com/voidlabs/mosaico/wiki/Saving-and-Loading
