### ISSUE TITLE
Default image in block

### ISSUE THREAD

**Issue by nasserqadri** [voidlabs/mosaico#384]
Is it possible to load a default image when you add a block, instead of the placeholder? I will always want the logo to be the same image every time I create an email, so it would be easier for it to automatically appear when I add that block, rather than having to move it from the gallery.

**Comment by Hiswe** [comment]
You should create a template with your default logo in it.
This is, I think, the simplest way of achieving what you want :)

**Comment by nasserqadri** [comment]
That's a great idea. Is it still possible to go back and change that file then? In the rare occasion that I want to swap that logo out for another image? 

Basically, I'd like a default image with the option to change it in case I need to.

**Comment by Hiswe** [comment]
You can make multiple logo blocks, or make a configurable logo block with a
select box maybe

**Comment by bago** [comment]
If you implement some sort of save/load template around mosaico then you will simply start cloning a previous template and you will already have the images you used the last time.

Otherwise if you want a default image instead of the "placeholder" have a look at this issue:
https://github.com/voidlabs/mosaico/issues/234

**Comment by nasserqadri** [comment]
Thanks very much - the **data-ko-placeholder-src="path"** functionality was exactly what I needed.
