### ISSUE TITLE
Moxiemanager to edit images. Where is it gone ?

### ISSUE THREAD

**Issue by dennisnovac** [voidlabs/mosaico#385]
Why does the mosaico.io website allow to edit images using Moxie, but there isn't such a option in this version on github?

Can you please share it, because image editing is pretty basic ?

Thanks.

**Comment by bago** [comment]
It is a licensing issue. AFAIK Moxiemanager cannot be integrated in a GPL application because it is not GPL.
On mosaico.io we use the commercial version of Mosaico and this let us use commercial integrations.

Integration code is pretty simple as mosaico provides extension points for that, but you cannot link a javascript GPL library to a commercial library.

**Comment by bago** [comment]
PS: if you know of a good GPL image editing library I can give you directions on how to integrate it.
