### ISSUE TITLE
install mosaico on debian 9

### ISSUE THREAD

**Issue by Vgratioulet** [voidlabs/mosaico#390]
Hello,
thanks for the great tool
I installed it on my debian 9.1 and I had to change few things from the manual to make it work, maybe it can be useful for someone else : 
- from https://www.npmjs.com/package/mosaico/tutorial
I replaced the command for Ubuntu 
`curl -sL https://deb.nodesource.com/setup | sudo -E bash -`
by
`curl -sL https://deb.nodesource.com/setup_6.x — Node.js v6 Current | sudo -E bash -`
in order to have nodejs 6 installed, otherwise it was nodejs 4

- from https://www.npmjs.com/package/mosaico
after `npm install mosaico` fails on dependency error, I had to change directory 
`cd node_modules/mosaico` so `npm install` can indeed fix the missing elements

- grunt builds successfully the server and launches it, and open the webpage in my brower
 at location 127.0.0.1:9006, but if I click on anything on the page I have a full red page.
The js console shows : 

> Unsupported minimized Knockout version 3.4.2 (supported DEBUG or minimized 3.2.0 … 3.4.1)

So I uninstalled bower-npm-install `npm uninstall bower-npm-install`, 
removed the directory bower_components/knockout which is v3.4.2
altered the file mosaico/bower.json to replace     `"knockout": "~3.4.0"`, by     `"knockout": "3.4.0 - 3.4.1"`,
then `npm install` followed by `grunt`
launches mosaico without error

**Comment by bago** [comment]
I don't know who pushed mosaico on npmjs but we don't support that method (I guess it is simply an old release that is broken because of no dependencies locking).

get a copy of the lastest release from github and try again.

**Comment by Vgratioulet** [comment]
you're right, from github sources,
in the downloaded folder 'npm install' then 'grunt' does the job, thanks

Then I only need 
for mosaico
```
/dist
editor.html
favicon.ico
index.html
```
for the data
```
/templates
/uploads
```
and whatever is needed for the backend

so I don't need 
```
/bower_components
/build
/res
/spec
/src
/tasks
/node_modules
bower.json
Gruntfile.js
package.json
server.config.js (as I don't use the nodejs backend)
Dockerfile (as I don't use docker)
Dockerfile.CentOS (as I don't use docker)
```
is that right ?

**Comment by bago** [comment]
That's almost right!

/templates is not backend stuff, but directly loaded/included by the frontend with no manipulation by the backend but "http serving". So it is like index.html.

If you don't use mosaico sample node backend you don't need "uploads". Otherwise if you want to use the bundled sample node backend you will need not only "uploads" but also the "backend" folder and the /node_modules needed by the "server" task, the server-config.js and more build stuff. At this time I didn't separate "backend" runtime dependencies from development dependencies.

**Comment by bago** [comment]
In other words...
in order to embed the library you need 
- the /dist content
- you have to include the js and instantiate mosaico in your code (or use index/editor.html)
- you have to provide at least a master template (so at least one from /templates or your own templates).
- a backend: you have to run a backend

https://github.com/voidlabs/mosaico/wiki/Serving-Mosaico
