### ISSUE TITLE
How to export a single block into HTML and Import the same after editing?

### ISSUE THREAD

**Issue by sibbu2005** [voidlabs/mosaico#392]
Hi, 
I want to create a source code editor for individual blocks. I have added a source code icon before the magic wand added to get the source code  in a dialog box and after edit it , replace the previous block code with new.

What I did:  Added this control in editor block in : 
`<div title="Source Code" class="tool source" data-bind="attr: { title: $root.t('Source Code') },click: $root.sourceCodeBlock.bind($element, $index, $parent)"><i class="fa fa-fw fa-code"></i></div>`
MY FUNCTION 
```
   viewModel.sourceCodeBlock=function(index, parent){
       var idx = ko.utils.unwrapObservable(index);
       console.log(idx);
       var unwrapped = ko.toJS(ko.utils.unwrapObservable(parent.blocks)[idx]);
       var htmlBlock=viewModel.exportHTML(unwrapped);
       console.log('Source Code METADATA',unwrapped);
       console.log('Source Code HTML',htmlBlock);
         };
```
I am getting an Object that has been used for duplicating the block.

Now how can I use this object to export into HTML and after editing import after changing to same object format.

**Comment by sibbu2005** [comment]
![editor](https://user-images.githubusercontent.com/4980123/34242955-6b6440b8-e644-11e7-93a1-0a139804c63d.png)

this is my implementation

**Comment by sibbu2005** [comment]
![screenshot](https://user-images.githubusercontent.com/4980123/34243002-af37fbb8-e644-11e7-96a8-7c5955ff9019.png)
I did many modification, as Pagination Style, Gallery search, sort, reload, Google Image serach , But this time i am not getting any clue.

**Comment by bago** [comment]
I'm sorry but there is not way to export the html for a single block. (your only option is export everything and find a way to extract the html for that block).

BTW you won't be able to import html anyway.. mosaico model is JSON tree.. you edit a JSON tree and you EXPORT an HTML. There is no "IMPORT" for HTML because the html is defined by the master template and mosaico does not edit the HTML. Mosaico simply customize/compose output. Mosaico does not understand HTML.

If you want to deal with custom HTML you can insert a "text block" and use the tinymce sourcecode button for that block.

**Comment by sibbu2005** [comment]
Thanks @bago  for your quick reply:)
