### ISSUE TITLE
width parameter is passed to null

### ISSUE THREAD

**Issue by tiagobernardes** [voidlabs/mosaico#42]
Some mosaics (images placeholders) in the width parameter is passed to null.

http://localhost:2628/TemplateBuilder/Img?src=..%2F..%2Fuploads%2FDesert.jpg&method=resize&params=320%2Cnull

someone tell me where can I fix this problem?

**Comment by bago** [comment]
This is not a "placeholder" request, but a "resize" request (look at the "method" parameter).

This is EXPECTED to have a null size because "resize" method is used to get a resized version of an image where you specify only the new width or the new height and the image you get keeps its original aspect ratio.

So, nothing weird here, just an expected request.

PS: the second parameter is the height, not the width.
