### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Gorgona9** [voidlabs/mosaico#438]
Hello.
I would like to ask if there is any other way to append Mosaico to the existing project besides npm install? As I need only Editor part.

**Comment by bago** [comment]
1) Read:
https://github.com/voidlabs/mosaico/blob/master/CONTRIBUTING.md

2) Read and build it using npm.
https://github.com/voidlabs/mosaico/blob/master/README.md

3) Once you built it you won't need npm anymore if you just want to include the built library. Otherwise download the "dist" package that includes already built library: https://github.com/voidlabs/mosaico/releases/download/v0.17.3/mosaico-0.17.3-dist.zip so you can ignore NPM at all.

4) Read the wikis
https://github.com/voidlabs/mosaico/wiki
https://github.com/voidlabs/mosaico/wiki/Serving-Mosaico

5) You probably don't "append" libraries to an existing project, but "integrate" them.

**Comment by Gorgona9** [comment]
Thanks a lot.

**Comment by Gorgona9** [comment]
Hi.... I have a problem again.... I am trying to integrate still. but no I have an error, which says, that 
Cannot read property 'core' of undefined
   at mosaico-lib.min.js?0488c5a6d25ce0c54e3469b75d5702a127f48e96:12

and ko.js is not generating in the bindings. I there any component I missed to add?
