### ISSUE TITLE
Make a Desktop application

### ISSUE THREAD

**Issue by bwl21** [voidlabs/mosaico#44]
Would it be possible to generate a desktop application of the editor e.g. using electron (https://github.com/atom/electron)

**Comment by bago** [comment]
I didn't know anything about electron, so I can't tell how hard it could be.

This is not a priority to me and I have no time to put my hands in electron, but I'm happy to help if anyone wants to try as it would be a good addition to the opensource project.

**Comment by bwl21** [comment]
I plan to give it a try. The very first thing I need to know is, which files are required at runtime. In other words, if I do a  `grund build` it would be good to deliver the runtime files into one folder. Is it the content of `dist`? 

Which means I need to pack `dist`, `index.html`, `templates`, `editor.html` ?

I plan to have a desktop app which does not require a server. It rather should save the file to the local file system.

I would need a javascript implementation of the premailer function.

I have done a similar thing with my zupfnoter (using node webkit). It was not that hard.

**Comment by bago** [comment]
Yes, the "frontend" files are then ones you told.

I think you can use the "backend" too, as electron seems to run a node.js instance. It already use a javascript inliner named "Stylizer":
https://github.com/voidlabs/mosaico/blob/master/backend/main.js#L113

I guess your main issue will be image manipulation because it depends on imagemagick being installed and I don't know if/how it could be bundled in the application. Unfortunately AFAIK there is no "pure javascript" (no dependencies) image manipulation libraries.

**Comment by bago** [comment]
Also, if you run in the desktop where do you upload images? When you send a test it currently put references to the uploaded images, but if you have them on your desktop you can't reference them from the email.

**Comment by bwl21** [comment]
Do I really need the "backend"? If yes, the desktop-app can indeed use the demo backend.

About image manipulation: there is http://camanjs.com/. We also could configure the path to image magic, such that it can be installed separately from mosaic-desktop.

About uploading images: I think I would let the user upload the images anywhere, and simply enter the url of the image. Alternatively, I configure some upload facility (e.g. an ftp-user) and URL - pattern for the images. Then the author could upload them and put the correct image url. In our workflow, we plan to select and pre-upload the images in advance.

**Comment by bago** [comment]
well, if you provide an URL for images then you  will have to implement dynamic download+resize+upload feature as you can't "live resize" an URL.

One of the "key feature" for mosaico is that you don't have to manually resize images because it automatically resize/crop them to fill your placeholder.

**Comment by bwl21** [comment]
I managed to get the editor up in electron. Of course the other things do not work yet, even going back to the index.html :-)

I see that handling of images is indeed an issue - maybe even a showstopper. Most of my ideas are shortcuts which probably end as detours.

The key feature of a desktop version should be that it does not require a server. If we need a server, it can easily serve the editor as well. Then the desktop version has not much additional value anymore which justifies the additional effort.

I therefore close it as wontfix.

**Comment by bago** [comment]
IMO the "best option" for a desktop application would be:
1) provide a download as ZIP
2) provide an S3 integration (or other file upload facilities) and have the "send-test" feature automatically upload local images and send (but this will make the "send test" very slow...). Maybe using an md5 of the image data as the file name would make it possible to skip uploading for already uploaded images.

Another solution would be to "embed" the images in the email, so that you don't need hosting: this is not something I suggest for "mass mailing" because embedded images increase the email size and the "spamminess" of the message, but this would make it possible to test the  message on the desktop.

**Comment by bwl21** [comment]
Yes, I thought in that direction. But a closer look reveals that the overall process gets more complicated and the benefit of a desktop application goes away. So for my project I will try to work with the PHP backend now.
