### ISSUE TITLE
Can the default background color be changed?

### ISSUE THREAD

**Issue by CaptainHypertext** [voidlabs/mosaico#442]
Is it possible to change the default background color?  It's #3F3F3F and I'd like to make it #FFFFFF.  I tried changing this in the template, but it broke with this error:

TODO error!!! Trying to set a new default value for frameTheme backgroundColor while it already exists (current: #3f3f3f, new: #FFFFFF)

**Comment by bago** [comment]
If you want to change a default color you have to make sure to change it everywhere (in every block sharing the same variable/theme), otherwise mosaico doesn't know what is the theme color.

So, the error is telling you that you have another backgroundColor in a "frameTheme"d block (header, footer, social) that is declared with a different color. Just change them to match and it will go ahead.

If you go to https://github.com/voidlabs/versafix-template you'll find that it is easier there to change
https://github.com/voidlabs/versafix-template/blob/master/template-def/template-versafix-1.htmml#L740
and 
https://github.com/voidlabs/versafix-template/blob/master/template-def/template-versafix-1.htmml#L794

**Comment by CaptainHypertext** [comment]
Thanks for the help, I'll check that out.
