### ISSUE TITLE
Align buttons in double- and triple-article blocks

### ISSUE THREAD

**Issue by shawnboy777** [voidlabs/mosaico#444]
Hello,
I was wondering if this could be added as a feature, or if you could explain how I may be able to make the buttons in the double and triple-article align based on the length of the text inside each.  Currently, if one text area is longer than the other, the buttons are out of alignment.  But visually, I think it would look cleaner if the buttons could line up, even if that means having white space between the shorter text and its button.

I tried to calculate the height of the longer text box and apply it to the shorter, but I can't seem to get it to work (not sure when my javascript is triggering in relation to the template's).

Thanks for looking into this!

Shawn

**Comment by bago** [comment]
Most of your recipients will see your 3 column blocks in mobile, with the columns one under the other. Your empty space to align the buttons will make them think the button belongs to the following block instead of the previous one, so I don't think it is a good idea.

That said, Mosaico library doesn't currently give you option to dynamically react to your contents (e.g altering the size of one block depending on the content of another) and I don't think this use case is interesting enough to implement such a complex feature.

On the other side, this can be done by using your own master template and putting buttons in their own table: you'll break responsivity, but you can do whatever you want in the master template with your own html.

**Comment by bago** [comment]
I close this as won't fix for the "library" part.
