### ISSUE TITLE
Add a way to exit from mosaico to "index" or another defined URL (Was: Editor does not return to index.html if installed in a subdirectory.)

### ISSUE THREAD

**Issue by bwl21** [voidlabs/mosaico#47]
I have installed mosaico in a subdirectory (http://www.weichel21.de/mosaico). When click on the mosaico icon in the editor it goes back to the root of the server but not to the mosaico page.

**Comment by bago** [comment]
I think I should remove the index<->editor moves and keep only one entry point. The editor itself should probably propose the template choice or the "load from saved session" when you invoke it with no hash.

The redirect is not something happening in the library but something defined in the editor.html and this should be simply considered an example: you shouldn't deploy the example index/editor as they are not thought for deployment.

**Comment by bwl21** [comment]
ok, I see that index is for demo only. On the other hand, management of templates and email should be outside of editor. Therefore index is not that bad for management of templates and emails. I cannot see how I can change editor.html to fix this issue.

**Comment by bago** [comment]
Here is where the redirect happen:
https://github.com/voidlabs/mosaico/blob/master/editor.html#L40

**Comment by bago** [comment]
BTW I just tried pushing mosaico to a subfolder and opening editor.html with no hash and it does correctly redirect to the index.html in the same path (it redirects to "." that the server try to lookup as "index.html").

So, I don't know what your issue is.
Where does it redirect you? Do you see javascript console logs?

**Comment by bwl21** [comment]
If you try it here: http://www.weichel21.de/mosaico. 
Open the editor and then click on the mosaico icon. It redirects to http://weichel21.de. You can see this when you hover on this icon.

**Comment by bago** [comment]
Ahhhh!! I didn't got you where talking about the "mosaico icon" on the top-left, sorry (I had in my mind the "missing hash redirect" and I didn't follow you).

That url is in src\tmpl\main.tmpl.html  in the "loading" box. That icon was not intended to "return to the index" but like "see what mosaico is", so it should probably link to "http://mosaico.io" on a new window.

In my official deploy I hide that icon (my users know mosaico as "Editor a blocchi").

**Comment by bwl21** [comment]
how else can I leave the editor?

Am 25.11.2015 um 00:02 schrieb Bago <notifications@github.com>:

**Comment by bago** [comment]
Good point...  in this case we probably neel a "back" button (a left-pointing arrow?) and a configuration option to define its url.

**Comment by bwl21** [comment]
In consequence editor configuration should allow to add custom buttons / dropdowns to the editor and connect the same with a callback or an url. This would also allow  to configure the editor to provide an "upload to Mailmanager" etc. I am not sure how this fits with editor plugins (which I do not understand yet).

**Comment by bago** [comment]
At this time mosaico provides 3 buttons extension points: "save", "test", "download". They appear if you define them in the viewModel (and you can do this via plugin).

BTW You can also add whatever HTML you want in the editor.html (this is how we deal with integration in our deployment: we put our buttons html in the page and then position then top-right via CSS).

**Comment by bago** [comment]
So, the "current way" to do both of this, is to make your own html in editor.html (editor.html is not part of the library, is just an example, so it is expected that you do your own things in that html).

You can change the visibility of the "mosaico logo" and position there your own "control" that will go back. And you can add buttons in the top-right corner to do your other "actions".

I want to better understand a few integration scenario before I do changes on this part, because I think every deployment/integration has its own special cases and the solution for one use case may be a show stopper for another...

**Comment by bwl21** [comment]
I played around with the approach of adding buttons to the editor as an overlay. It is pretty difficult to place it correctly. And it is also somehow dependant from mosaico. I still would prefer a plugin approach.

Is it reasoable to manipulate <div class="rightButtons"> via javascript?

**Comment by bago** [comment]
Isn't it enough to position it "absolutely"? (you should remove the "localstorage" plugin given you don't use it anymore and use the "top-right" area as you like.
```
<div id="mybutton" class="mo button" style="position: absolute; z-index: 200; top: 2px; right: 2px;">my button</div>
```

I'm not yet ready to work on "pluggability" for this kind of integration (as I already said, I want to show multiple deployment scenario before I make it pluggable), so I won't implement it in the short term.

Of course any contribution is welcome, but I don't think it worth it if the issue is just to "place it correctly".

**Comment by bwl21** [comment]
Of course I understand that. How can I remove "localstorage" plugin? If I can remove it, couldn't I as well inject another plugin or enhance "localstorage" plugin?
