### ISSUE TITLE
css loader gif should be removed

### ISSUE THREAD

**Issue by charles-lebrun** [voidlabs/mosaico#470]
Hello there is two line on your css that fail compilation, because image doesn't exist, could we remove it ?

https://github.com/voidlabs/mosaico/blob/881d673073afebd868ec3fb8ed2454641865243d/src/css/style_elements.less#L495

https://github.com/voidlabs/mosaico/blob/881d673073afebd868ec3fb8ed2454641865243d/src/css/style_elements.less#L500

**Comment by bago** [comment]
How are you compiling this?

I guess the 2 rules are not applied at all in mosaico.. mosaico code have been extracted from a larger application and opensourced, so there is some code (expecially in css) that is not really used by mosaico, but is there because it makes it simpler for us to maintain it.

**Comment by bago** [comment]
No answers, closing this.
