### ISSUE TITLE
Safari issue with latest version

### ISSUE THREAD

**Issue by godara-ravi** [voidlabs/mosaico#500]
Hi Support,

Mosaico does't work anymore in safari latest version. I am using safari version 12.

![safari_issue](https://user-images.githubusercontent.com/47026411/52263742-f623a180-2955-11e9-9181-3a24e0aabfd2.PNG)

Note: the original editor (mosaico.io) also have this issue. And i run macOS Mojave with the latest Safari version.

**Comment by bago** [comment]
I bet you have some extension "mungling" pages, like Grammarly.
Can you tell me the output from this page opened with your Safari?
https://mosaico.io/controlloalterazioni.html

**Comment by Hiswe** [comment]
@bago no problems on Safari `12.0.2` 
But if the extensions are a problem, I guess you could write it in the warning popup and put a link on the `alteration control` page…

I don't think it's in the Mosaico's codebase, so can't come with a PR

**Comment by bago** [comment]
@Hiswe there are plenty of weird extensions. I don't want to put a link to a very weird page like "controllo alternazioni" because 1 user over a million have some extension breaking the HTML. What would be the point? A final user won't be happier with a "controllo alterazioni" output. We can't even be sure we are able to detect all of the breaking extensions. I just included some basic code that write some HTML and then look if the html written is the same that I wanted to write or if something else altered the code and then I put an "this is not compatible". I can't know why extensions or browsers may want to alter HTML, so I can simply tell that I don't expect it to be compatible. I prefer to give this error because when your browser alters the HTML then you may experience very weird behaviour with the output of mosaico, and you could think mosaico put something in the HTML while your browser/extension did that. AFAIK Chrome recently banned extensions altering HTML this way.

It's in the main code:
https://github.com/voidlabs/mosaico/blob/master/src/js/template-loader.js#L382

In the latest code "isCompatible" method can take a "true" parameter and this will make it throw an exception (with some details) instead of returning "false".

**Comment by Hiswe** [comment]
@bago thanks for the detailed answer. 
And yes, that make sense :)

**Comment by bago** [comment]
Unfortunately @godara-ravi didn't reply yet.

**Comment by godara-ravi** [comment]
@bago, it was extension issue. Thanks!
