### ISSUE TITLE
How to append some else Image editor to Mosaico?

### ISSUE THREAD

**Issue by minkookBae** [voidlabs/mosaico#505]
Hello, I'm trying to make an web page with my colleague.
And, we met a problem with this.

In Demo live, Mosaico uses moxiemanager for image editing.
So, we tried to append to our environment, but moxiemanager is not free and can be used only php and .net back-end.. (we made back-end with node.js)

Finally, we find [Toast ui image editor](https://github.com/nhnent/tui.image-editor) with MIT license.
we found some way to append image editor(change viewModel.editimage in viewModel.js)

but, we are struggling now..
Could you help me a little bit?

**Comment by bago** [comment]
On the editor page, as a parameter to Mosaico.init() pass your custom "plugin":

```
var imageEditorPlugin = function(vm) {
  
  // adds image editing option to Mosaico
  vm.editImage = function(src, done) {
    // call your image editor and once you're done call 
    // src(vm.remoteUrlProcessor(newUrl));
    // with the url of the edited image.
  };

};
```

You'll have to study Toast ui image editor in order to see how you can insert it into the html page and how to invoke it. On "Mosaico side" you just have to implent that method that give you the url of the image to be edited and expect back a new url of the edited image.

**Comment by minkookBae** [comment]
Thank you, bago !

**Comment by bago** [comment]
Please share your resulting plugin if you succeed!

**Comment by melongl11** [comment]
Hi I am a colleague of minkookBae.
I just succeeded to append the tui image editor to mosaico. But I have a problem. After saving the image to the server, the gallery thumbnail and the image loaded in the block do not change even if you quit the tui image editor(I call the remoteUrlProcessor function too).
 When I saved the image to the server, I saved it to the same url I currently saved. Is it because of that?
 Can you tell me how to refresh the gallery and images?

**Comment by bago** [comment]
Please share your branch on github in a way I can see the integration code and run it easily and I'll have a look.

**Comment by melongl11** [comment]
Here is my branch.
https://github.com/melongl11/mosaico

The gallery and thumbnail still do not change...

**Comment by bago** [comment]
I downloaded it, built/run, uploaded an image, clicked on the "edit image" (pencil) button, but I get: "Uncaught ReferenceError: blackTheme is not defined" and nothing happens.

**Comment by melongl11** [comment]
Sorry, tui image editor needs to some files to the dist folder. So I added the dist folder to my branch.

**Comment by bago** [comment]
Your "upload_edited" backend doesn't tell anyone the file name used to save the content.
Once you return the url, you'll have to call
"src(newImageUrl)" in your "success" handler for your editImage implementation.
You may want to also call "viewModel.loadImage(newImageUrl)" if you want the new image to be shown in the "recent" gallery.

**Comment by melongl11** [comment]
I thought I did not need to return url because I made the url of the original image equal to the image I saved after the modification.
So I think the reason why the image of the added block is not changed is that the path of the stored image after modification is the same as the path of the original image. The image of the added block was changed when I tried to change the path of the modified image from the original image. 


 However, no modified thumbnails are added to the recent gallery. When I load an image, I put the image as a parameter to viewModel.loadImage(image). In the success function, I put url of the image as a parameter of viewModel.loadImage(url). Is it possible to put the url as parameter of viewModel.loadImage function?

**Comment by bago** [comment]
If you change an image content you HAVE TO change the url/path otherwise you'll get a lot of caching issues in mosaico and outside.

The "img" parameter to loadImage is an object with the same format of the "/upload" backend service.
```
{
"name":"addition-black-and-white-black-and-white-374918.jpg",
"size":344611,
"url":"https:\/\/....374918.jpg",
"thumbnailUrl":"https:\/\/...374918.jpg"
}

```
If urls didn't change mosaico won't reload them, or mosaico will reload it and the browser will show outdated content from the cache.

The "right" thing to do is to change the server side upload for TUI so that it uses a new name and returns a JSON with the above format (like the default upload service does).

**Comment by bago** [comment]
(another thing that would break if you don't change the name is the undo/redo as you won't be able to undo an image editing if you overwritten the original one)

**Comment by melongl11** [comment]
I finally succeeded in adding an image editor.
In the success function, the parameter of src function must be the new url of image, but the viewModel.loadImage function must be set to an object with the same format of the "/upload" backend service. 
Thank you, Bago.
