### ISSUE TITLE
how can we create template level border?

### ISSUE THREAD

**Issue by ramachandranvenkat** [voidlabs/mosaico#508]
I need to create border which should be outside of (mainblocks) all the blocks and size and color has to be controlled dynamically.

Please let me know how it can be achieved using mosaico.

**Comment by bago** [comment]
This is not a mosaico thing, but a master template thing. Versafix-1 our main master template, is a full width blocks template, so you can't add a border outside them (you can, but it would not be in the place you want). But you can make your own template using borders, but you'll need html email template experience in order to make a solid template that will work on email clients.

https://github.com/voidlabs/mosaico/wiki/Template-language
https://github.com/voidlabs/versafix-template

**Comment by ramachandranvenkat** [comment]
I am looking for similar to versafix-template with border added to it. 
as attached ...




![image-border](https://user-images.githubusercontent.com/16936469/54416777-5c0a0280-4726-11e9-8f7f-872dffca6354.jpg)

**Comment by bago** [comment]
I understood it. my previous answer is still valid. This is not a mosaico library thing. Mosaico library doesn't even know what a border is. Mosaico just let's you edit a  master template: so you're looking for a master template with a border. No one contributed such a template, so you'll have to create your own.
