### ISSUE TITLE
 inliner should be implemented in the client

### ISSUE THREAD

**Issue by bwl21** [voidlabs/mosaico#54]
I think that the inliner should be implemented in the client side inside mosaico so it is done the same way with no "intelligence" in the backend: the backend should be as dummy as possible and inlining is not a dummy thing (nor a "known transformation" as there is no "one good way to inline").

**Comment by bago** [comment]
We currently use Styliner in the node.js backend but we cannot use it on the client-size for this issue:
1) it does not run in the client
2) it does not support "unknown" properties or multiple properties with the same name in the same property-set
3) id does not support our "data-inline" attribute.

Maybe we can take some code from Styliner, change the parser to Mensch and then use jQuery to manipulate the resulting code.

**Comment by bwl21** [comment]
How bad. This sounds like a lot of work.

**Comment by bago** [comment]
Just an update to this issue.

We investigated how well known inliners works:
http://mosaico.io/email-client-tricks/email-inliners/

At the end we chose [Juice](https://github.com/Automattic/juice/) because it was easier to adapt to our need. Juice author was happy to accept and merge our patches to fix the most critical Juice issues and I'm working on the last patch so to make it useable by mosaico.
