### ISSUE TITLE
Share block links not editable

### ISSUE THREAD

**Issue by louis71barker** [voidlabs/mosaico#544]
Hi, 

We don't seem to be able to edit the URL links for the share block social links. This also seems to be an issue on your demo page also, unless i am missing something obvious. Is this a known issue and do we need to implement the link editing or have i missing something with this block?

Many Thanks for any help that could be given

**Comment by bago** [comment]
This is something defined by the master-template and it "designed" to work that way.

You create a template that you will have to manipulate in order to put your own unsubscribe/view in a browser links or to add link tracking. In the same procedure you will put your own sharing links there: in order to share you have to create a webpage with a static url that will publish your email on the web and your tool will know where it has been deployed and how to fill it in the sharing links. This is not something that the editor itself can do (the editor doesn't deploy anything, is just a library to edit the condent).

**Comment by bago** [comment]
Of course you can create your own master template (or alter an existing one) in order to let people manually write their url there, if you need that, but it would be weird to ask your user to put the url where the email will be published, when the email doesn't exists yet, as they are still editing it.

**Comment by louis71barker** [comment]
Okay i see, that makes sense now with the use case :) 
Thanks for the quick reply!
Great tool by the way!!!
