### ISSUE TITLE
where is documentation?

### ISSUE THREAD

**Issue by faizananwerali** [voidlabs/mosaico#608]
I can't figure out where to start.

All I see is text in WIKI, there is no Javascript code documentation.

Where is it?

Where are compiled js and CSS files?

**Comment by bago** [comment]
Did you read the README?
This tells you how to compile (build) the project:
https://github.com/voidlabs/mosaico/blob/master/README.md#buildrun-with-the-development-backend-

Otherwise you find prebuilt artifacts in the "dist.zip" files in the releases:
https://github.com/voidlabs/mosaico/releases

Mosaico is a javascript library targeting developers, don't expect to be able to use it if you can't develop a "backend":
https://github.com/voidlabs/mosaico/wiki/Serving-Mosaico
