### ISSUE TITLE
provide template specific hints to the email author (was: define placeholder in the template such that the user does not need to remove text provided by template.)

### ISSUE THREAD

**Issue by bwl21** [voidlabs/mosaico#62]
When I create an email based on versaflex-1, insert e.g. IMAGE+Text block, I have to select and remove the "lorem ipsum" injected by the block. It would be good if there is a way to markup this text in the template as "placeholder" which vanishes as soon as the author starts typing.

We could even go that far, that this text can be used as kind of instruction for the author which appears as tooltip or in a "instruction pane" (which would be dess distracting).

**Comment by bago** [comment]
I thought at this in past. I didn't do this because:
1) the base text MAY be good for sending the email (e.g: most people will not change the "Unsubscribe" text)
2) Some user MAY want to simply leave a text empty, so if you implement a "placeholder" that appears when the content is empty you create an issue to them.
3) "Placeholder" and "tinymce" didn't work really good when I tested.
4) Deleting the default content is not something hard, and the current behaviour is not "less expected" than the one provided by a "placeholder".
5) This would have introduced one more template language construct (because of n.1).

If you think you have an idea for them to be implemented without these issues, please write down.

Questions:
1) If I export without touching anything, do I see the "placeholder text" or "empty"?
2) the placeholder text disappear as soon as a clic on the text?
3) if I leave the editor just after clicking (without changing anything) does the placeholder come back?
4) if I empty a content, does the placeholder text come back?

**Comment by bwl21** [comment]
Thanks for sharing your experience. I see there is no simple solution for this. So going a step back, the basic request is:

* user should not need to select existing content in order to clean the element. At least it should be very easy. Maybe cmd-a, cmd-x is even easy enough.
* If content is empty, user should still be able to locate the elements to see where he can enter content. as of now it is only upon hovering the area with the mouse.
* Template author should be able to give hints to the user. Maybe this can be achieved by the given means. There could be a page wide class called "show hints" which controls the display of the hints. I played around in versaflex-1 but did not manage to make button visible depending on `preheaderVisible`.

**Comment by bago** [comment]
I played around in versaflex-1 but did not manage to make button visible depending on preheaderVisible.

I'm not following you... how does this "button" is related to "preheaderVisible"? And how both relate to the placeholder thing?

**Comment by bwl21** [comment]
for test purposes, i wanted to bind the visibility of a button to the visibility of the preheader. I wanted to see if such a global visibility of block content could be used to show/hide hints from the template author to the email author (third item).

**Comment by bago** [comment]
If you are on the "root template":
```
<yourtag data-ko-display="preheaderVisible">
you content
</yourtag>
```
If you are inside a block:
```
<yourtag data-ko-display="_root_.preheaderVisible">
your content
</yourtag>
```

BTW This is not intended for "editing hints": what you write will be exported in the HTML when shown to the user.

**Comment by bwl21** [comment]
Thanks. I had tried with $root (as in knockout ...). Sure, it is not for editing hints. It was an experiment if something like this could be used for the same without introducing more template language construct.

I tried it and it works at least as workaround.

You may close or add an "idea" - tag ...

**Comment by bago** [comment]
I currently don't see this as a generic feature with good usability/cost ratio, so I close it. 

IMO you can give some instructions via "default template text".

We already have "help" and "blockDescriptions" properties to add template specific instructions. Help has to be used on single properties and will show a tooltip activated by a "?" near the property.
blockDescription has to be used at block-type level and will show up in the left sidebar when a block of this type is selected.

**Comment by bwl21** [comment]
I will add this to the tutorial ...
