### ISSUE TITLE
use gitter.im for discussions

### ISSUE THREAD

**Issue by bwl21** [voidlabs/mosaico#78]
I see a lot of discussions going on and Issues opened which are more on a discussion level. I know that I produce some of them.

maybe it is worth to create a room on gitter.im for mosaico. As an example https://gitter.im/opal/opal is the room where many things are discussed before they are solved or boil down to a github issue.

gitter.im allows to create chatrooms related to github projects. It uses github flavored markdown and interacts well with github.

**Comment by bago** [comment]
Never used it, but sounds "flat". It works fine when you have a group of active developers that need to sync over a single task/decision. I don't think this is the case for mosaico... 

I added a wiki page for a brief introduction to plugins: https://github.com/voidlabs/mosaico/wiki/Mosaico-Plugins  so that I will try to push new stuff to that page.

**Comment by bwl21** [comment]
none of the other active people gave a comment ... so it seems that no other user wants to group.
