### ISSUE TITLE
3 Column blocks and 2 column blocks weird after changing the background color

### ISSUE THREAD

**Issue by kbalajijan1** [voidlabs/mosaico#85]
Try this:
1. Add 3 or 2 column blocks.
2. Click Style tab and change the background color of 3 column block
3. Move back or hover the cursor to the 3 column block's template area 

![3block_issue](https://cloud.githubusercontent.com/assets/8971969/11756869/eee7c4f0-a082-11e5-8863-55a29ee6e2cf.png)

Same thing happens to 2 column block. 

In Mosaico site it works fine but I can reproduce the issue with GIT codes

Thanks.

**Comment by bago** [comment]
Sh*t.. this may have to do with #53.
Can you tell me your browser/version/OS? And if you have multiple browsers, tell me which combination show this issue and which ones do not.

Thank you.

**Comment by kbalajijan1** [comment]
I use Ubuntu 14.04 and Chrome 45.x but It doesn't happen in Firefox(40.x).

I am unable to reproduce the issue, both in Chrome and FF, in http://mosaico.io/ but only in Github code I have this issue.

Thanks.

**Comment by bago** [comment]
The issue sounds very similar to the one fixed in #53 that was only visible in Safari. I reproduced your issue in Chrome, too, but this time it seems chrome add some spacing on the left and this way the layout breaks.. if you do anything like setting/resetting a css property then the layout is recomputed correctly (this is a proof it is a bug in the rendering engine and not something in our code, IMO).

BTW, mosaico.io is a few commit outdate (25th november, IIRC).

Can you test altering the "src\css\safarihack.css " to add a space between "and" and the bracket, e.g, from: "and("  to "and (" and tell me if you see the same issue?
The "safarihack" is the hack I had to introduce to force Safari do some more "reflow" and avoid its layout issues. The missing space is an "hack" to avoid that media query to be seen by Chrome (so it is selective for Safari), but maybe we should broad it to Chrome, too...

**Comment by kbalajijan1** [comment]
I don't see the issue after adding the space.

**Comment by bago** [comment]
Good news it's easy to fix. Bad news we have to apply those f***ing hacks to minimize weird bugs in modern browsers and force them to do much more work just to hope they do the right thing when they work much more.
